### ISSUE TITLE
None vibration setting doesn't work

### ISSUE THREAD

**Issue by ghost** [nahtedetihw/MusicQueueBeGone#1]
I have it selected and it still does a haptic effect similar to the finger lock bug if that helps at all. Also with no noise selected i still hear a noise

**Comment by nahtedetihw** [comment]
This has been fixed, version 1.3 was just uploaded to Twickd Repo.

**Comment by ghost** [comment]
It still vibrates sadly

**Comment by nahtedetihw** [comment]
There must be something else conflicting with it then

**Comment by ghost** [comment]
I just used I cleaner and disabled everything but your tweak. Still the same result :/ so it can't be a conflicting tweak

**Comment by nahtedetihw** [comment]
Are you on iOS 13?

**Comment by ghost** [comment]
Yes iPhone XR 13.3 and I used iCleaner to disable everything else and it still happens
